name: dd_base
description: A Flutter package with dd_base.
version: 0.0.2
homepage: https://github.com/flutter-dd/dd_base

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

