name: dd_base
description: A Flutter package with dd_base, .
version: 0.0.12
homepage: https://github.com/flutter-dd/dd_base

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  artemis: '>=5.0.0 <6.0.0'
  meta: '>=1.0.0 <2.0.0'
  gql: '>=0.7.3 <1.0.0'
  http: '>=0.0.1 <1.0.0'
  flustars: '>=0.0.1 <1.0.0'
  gql_http_link: '>=0.0.1 <1.0.0'
  json_annotation: '>=3.0.0 <4.0.0'

